// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebScrapping_Foods.Models;

public partial class FoodNutritionInfo
{
    public long Id { get; set; }

    public long IdUnitMeasurement { get; set; }

    public long? Quantity { get; set; }

    public long? IdNutritionalComposition { get; set; }

    public virtual ICollection<Food> Foods { get; set; } = new List<Food>();

    public virtual NutritionalComposition IdNutritionalCompositionNavigation { get; set; }
}