// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebScrapping_Foods.Models;

public partial class Food
{
    public long Id { get; set; }

    public string Name { get; set; }

    public double Quantity { get; set; }

    public long? IdFoodNutritionInfo { get; set; }

    public long? IdFoodGroup { get; set; }

    public string ReferenceTable { get; set; }

    public virtual FoodGroup IdFoodGroupNavigation { get; set; }

    public virtual FoodNutritionInfo IdFoodNutritionInfoNavigation { get; set; }
}